services:
  ai-project-visualizer:
    build: .
    container_name: ai-project-visualizer
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - APP_NAME=AI Project Visualizer
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-visualizer-network

networks:
  ai-visualizer-network:
    driver: bridge
